using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FF8_Memory_Reader
{
    public class FFVIIILocation
    {
        public Dictionary<int, string> locationList { get; }

        public FFVIIILocation()
        {
            locationList = new Dictionary<int, string>();

            locationList.Add(1, "Balamb- Alcauld Plains");
            locationList.Add(2, "Balamb- Gaulg Mountains");
            locationList.Add(3, "Balamb- Rinaul Coast");
            locationList.Add(4, "Balamb- Raha Cape");
            locationList.Add(5, "Timber- Roshfall Forest");
            locationList.Add(6, "Timber- Mandy Beach");
            locationList.Add(7, "Timber- Obel Lake");
            locationList.Add(8, "Timber- Lanker Plains");
            locationList.Add(9, "Timber- Nanchucket Island");
            locationList.Add(10, "Timber- Yaulny Canyon");
            locationList.Add(11, "Dollet- Hasberry Plains");
            locationList.Add(12, "Dollet- Holy Glory Cape");
            locationList.Add(13, "Dollet- Long Horn Island");
            locationList.Add(14, "Dollet- Malgo Peninsula");
            locationList.Add(15, "Galbadia- Monterosa Plateau");
            locationList.Add(16, "Galbadia- Lallapalooza Canyon");
            locationList.Add(17, "Timber- Shenand Hill");
            locationList.Add(18, "Galbadia- Gotland Peninsula");
            locationList.Add(19, "Island Closest to Hell");
            locationList.Add(20, "Great Plains of Galbadia");
            locationList.Add(21, "Galbadia- Wilburn Hill");
            locationList.Add(22, "Galbadia- Rem Archipelago");
            locationList.Add(23, "Galbadia- Dingo Desert");
            locationList.Add(24, "Winhill- Winhill Bluffs");
            locationList.Add(25, "Winhill- Humphrey Archipelago");
            locationList.Add(26, "Trabia- Winter Island");
            locationList.Add(27, "Trabia- Sorbald Snowfield");
            locationList.Add(28, "Trabia- Eldbeak Peninsula");
            locationList.Add(30, "Trabia- Hawkwind Plains");
            locationList.Add(31, "Trabia- Albatross Archipelago");
            locationList.Add(32, "Trabia- Bika Snowfield");
            locationList.Add(33, "Trabia- Thor Peninsula");
            locationList.Add(35, "Trabia- Heath Peninsula");
            locationList.Add(36, "Trabia- Trabia Crater");
            locationList.Add(37, "Trabia- Vienne Mountains");
            locationList.Add(38, "Esthar- Mordred Plains");
            locationList.Add(39, "Esthar- Nortes Mountains");
            locationList.Add(40, "Esthar- Fulcura Archipelago");
            locationList.Add(41, "Esthar- Grandidi Forest");
            locationList.Add(42, "Esthar- Millefeuille Archipelago");
            locationList.Add(43, "Great Plains of Esthar");
            locationList.Add(44, "Esthar City");
            locationList.Add(45, "Esthar- Great Salt Lake");
            locationList.Add(46, "Esthar- West Coast");
            locationList.Add(47, "Esthar- Sollet Mountains");
            locationList.Add(48, "Esthar- Abadan Plains");
            locationList.Add(49, "Esthar- Minde Island");
            locationList.Add(50, "Esthar- Kashkabald Desert");
            locationList.Add(51, "Island Closest to Heaven");
            locationList.Add(52, "Esthar- Talle Mountains");
            locationList.Add(53, "Esthar- Shalmal Peninsula");
            locationList.Add(54, "Centra- Lolestern Plains");
            locationList.Add(55, "Centra- Almaj Mountains");
            locationList.Add(56, "Centra- Lenown Plains");
            locationList.Add(57, "Centra- Cape of Good Hope");
            locationList.Add(58, "Centra- Yorn Mountains");
            locationList.Add(59, "Esthar- Cactuar Island");
            locationList.Add(60, "Centra- Serengetti Plains");
            locationList.Add(61, "Centra- Nectar Peninsula");
            locationList.Add(62, "Centra- Centra Crater");
            locationList.Add(63, "Centra- Poccarahi Island");
            locationList.Add(64, "B-Garden- Library");
            locationList.Add(65, "B-Garden- Front Gate");
            locationList.Add(66, "B-Garden- Classroom");
            locationList.Add(67, "B-Garden- Cafeteria");
            locationList.Add(68, "B-Garden- MD Level");
            locationList.Add(69, "B-Garden- 2F Hallway");
            locationList.Add(70, "B-Garden- Hall");
            locationList.Add(71, "B-Garden- Infirmary");
            locationList.Add(72, "B-Garden- Dormitory Double");
            locationList.Add(73, "B-Garden- Dormitory Single");
            locationList.Add(74, "B-Garden- Headmaster's Office");
            locationList.Add(75, "B-Garden- Parking Lot");
            locationList.Add(76, "B-Garden- Ballroom");
            locationList.Add(77, "B-Garden- Quad");
            locationList.Add(78, "B-Garden- Training Center");
            locationList.Add(79, "B-Garden- Secret Area");
            locationList.Add(80, "B-Garden- Hallway");
            locationList.Add(81, "B-Garden- Master Room");
            locationList.Add(82, "B-Garden- Deck");
            locationList.Add(83, "Balamb- The Dincht's");
            locationList.Add(84, "Balamb Hotel");
            locationList.Add(85, "Balamb- Town Square");
            locationList.Add(86, "Balamb- Station Yard");
            locationList.Add(87, "Balamb Harbor");
            locationList.Add(88, "Balamb- Residence");
            locationList.Add(89, "Train");
            locationList.Add(90, "Car");
            locationList.Add(91, "Inside Ship");
            locationList.Add(92, "Fire Cavern");
            locationList.Add(93, "Dollet- Town Square");
            locationList.Add(94, "Dollet- Lapin Beach");
            locationList.Add(95, "Dollet Harbor");
            locationList.Add(96, "Dollet Pub");
            locationList.Add(97, "Dollet Hotel");
            locationList.Add(98, "Dollet- Residence");
            locationList.Add(99, "Dollet- Comm Tower");
            locationList.Add(100, "Dollet- Mountain Hideout");
            locationList.Add(101, "Timber- City Square");
            locationList.Add(102, "Timber TV Station");
            locationList.Add(103, "Timber- Forest Owls' Base");
            locationList.Add(104, "Timber Pub");
            locationList.Add(105, "Timber Hotel");
            locationList.Add(106, "Timber- Train");
            locationList.Add(107, "Timber- Residence");
            locationList.Add(108, "Timber- TV Screen");
            locationList.Add(109, "Timber- Editorial Department");
            locationList.Add(110, "Timber Forest");
            locationList.Add(111, "Galbadia Garden- Front Gate");
            locationList.Add(112, "G-Garden- Station");
            locationList.Add(113, "G-Garden- Hall");
            locationList.Add(114, "G-Garden- Hallway");
            locationList.Add(115, "G-Garden- Reception Room");
            locationList.Add(116, "G-Garden- Classroom");
            locationList.Add(117, "G-Garden- Clubroom");
            locationList.Add(118, "G-Garden- Dormitory");
            locationList.Add(119, "G-Garden- Elevator Hall");
            locationList.Add(120, "G-Garden- Master Room");
            locationList.Add(121, "G-Garden- Auditorium");
            locationList.Add(122, "G-Garden- Athletic Track");
            locationList.Add(123, "G-Garden- Stand");
            locationList.Add(124, "G-Garden- Back Entrance");
            locationList.Add(125, "G-Garden- Gymnasium");
            locationList.Add(126, "Deling- Presidential Residence");
            locationList.Add(127, "Deling City- Caraway's Mansion");
            locationList.Add(128, "Deling City- Station Yard");
            locationList.Add(129, "Deling City- City Square");
            locationList.Add(130, "Deling City- Hotel");
            locationList.Add(131, "Deling City- Club");
            locationList.Add(132, "Deling City- Gateway");
            locationList.Add(133, "Deling City- Parade");
            locationList.Add(134, "Deling City- Sewer");
            locationList.Add(135, "Galbadia D-District Prison");
            locationList.Add(136, "Desert");
            locationList.Add(137, "Galbadia Missile Base");
            locationList.Add(138, "Winhill Village");
            locationList.Add(139, "Winhill Pub");
            locationList.Add(140, "Winhill- Vacant House");
            locationList.Add(141, "Winhill- Mansion");
            locationList.Add(142, "Winhill- Residence");
            locationList.Add(143, "Winhill- Hotel");
            locationList.Add(144, "Winhill- Car");
            locationList.Add(145, "Tomb of the Unknown King");
            locationList.Add(146, "Fishermans Horizon");
            locationList.Add(147, "FH- Residential Area");
            locationList.Add(148, "FH- Sun Panel");
            locationList.Add(149, "FH- Mayor's Residence");
            locationList.Add(150, "FH- Factory");
            locationList.Add(151, "FH- Festival Grounds");
            locationList.Add(152, "FH- Hotel");
            locationList.Add(153, "FH- Residence");
            locationList.Add(154, "FH- Station Yard");
            locationList.Add(155, "FH- Horizon Bridge");
            locationList.Add(156, "FH- Seaside Station");
            locationList.Add(157, "FH- Great Salt Lake");
            locationList.Add(158, "FH- Mystery Building");
            locationList.Add(159, "Esthar- City");
            locationList.Add(160, "Esthar- Odine's Laboratory");
            locationList.Add(161, "Esthar- Airstation");
            locationList.Add(162, "Lunatic Pandora Approaching");
            locationList.Add(163, "Esthar- Presidential Palace");
            locationList.Add(164, "Presidential Palace- Hall");
            locationList.Add(165, "Presidential Palace- Hallway");
            locationList.Add(166, "Presidential Palace- Office");
            locationList.Add(167, "Dr. Odine's Laboratory- Lobby");
            locationList.Add(168, "Dr. Odine's Laboratory- Lab");
            locationList.Add(169, "Deleted");
            locationList.Add(170, "Lunar Gate");
            locationList.Add(171, "Lunar Gate- Concourse");
            locationList.Add(172, "Lunar Gate- Deep Freeze");
            locationList.Add(173, "Esthar Sorceress Memorial");
            locationList.Add(174, "Sorceress Memorial- Entrance");
            locationList.Add(175, "Sorceress Memorial- Pod");
            locationList.Add(176, "Sorceress Memorial- Ctrl Room");
            locationList.Add(177, "Tears' Point");
            locationList.Add(178, "Lunatic Pandora Laboratory");
            locationList.Add(179, "Emergency Landing Zone");
            locationList.Add(180, "Spaceship Landing Zone");
            locationList.Add(181, "Lunatic Pandora");
            locationList.Add(182, "Centra- Excavation Site");
            locationList.Add(183, "Edea's House");
            locationList.Add(184, "Edea's House- Playroom");
            locationList.Add(185, "Edea's House- Bedroom");
            locationList.Add(186, "Edea's House- Backyard");
            locationList.Add(187, "Edea's House- Oceanside");
            locationList.Add(188, "Edea's House- Flower Field");
            locationList.Add(189, "Centra Ruins");
            locationList.Add(190, "Trabia Garden- Front Gate");
            locationList.Add(191, "T-Garden- Cemetery");
            locationList.Add(192, "T-Garden- Garage");
            locationList.Add(193, "T-Garden- Festival Stage");
            locationList.Add(194, "T-Garden- Classroom");
            locationList.Add(195, "T-Garden- Athletic Ground");
            locationList.Add(196, "Mystery Dome");
            locationList.Add(197, "Shumi Village- Desert Village");
            locationList.Add(198, "Shumi Village- Elevator");
            locationList.Add(199, "Shumi Village- Village");
            locationList.Add(200, "Shumi Village- Residence");
            locationList.Add(201, "Shumi Village- Residence");
            locationList.Add(202, "Shumi Village- Residence");
            locationList.Add(203, "Shumi Village- Hotel");
            locationList.Add(204, "Trabia Canyon");
            locationList.Add(205, "White SeeD Ship");
            locationList.Add(206, "White SeeD Ship");
            locationList.Add(207, "White SeeD Ship- Cabin");
            locationList.Add(208, "Ragnarok- Cockpit");
            locationList.Add(209, "Ragnarok- Passenger Seat");
            locationList.Add(210, "Ragnarok- Aisle");
            locationList.Add(211, "Ragnarok- Hangar");
            locationList.Add(212, "Ragnarok- Entrance");
            locationList.Add(213, "Ragnarok- Air Room");
            locationList.Add(214, "Ragnarok- Space Hatch");
            locationList.Add(215, "Deep Sea Research Center");
            locationList.Add(216, "Deep Sea Research Center- Lb");
            locationList.Add(217, "Deep Sea Research Center- Lv");
            locationList.Add(218, "Deep Sea Deposit");
            locationList.Add(219, "Lunar Base- Control Room");
            locationList.Add(220, "Lunar Base- Medical Room");
            locationList.Add(221, "Lunar Base- Pod");
            locationList.Add(222, "Lunar Base- Dock");
            locationList.Add(223, "Lunar Base- Passageway");
            locationList.Add(224, "Lunar Base- Locker");
            locationList.Add(225, "Lunar Base- Residential Zone");
            locationList.Add(226, "Outer Space");
            locationList.Add(227, "Chocobo Forest");
            locationList.Add(228, "Wilderness");
            locationList.Add(229, "Ultimecia Castle- Hall");
            locationList.Add(230, "Ultimecia Castle- Grand Hall");
            locationList.Add(231, "Ultimecia Castle- Terrace");
            locationList.Add(232, "Ultimecia Castle- Wine Cellar");
            locationList.Add(233, "Ultimecia Castle- Passageway");
            locationList.Add(234, "Ultimecia Castle- Elevator Hall");
            locationList.Add(235, "Ultimecia Castle- Stairway Hall");
            locationList.Add(236, "Ultimecia Castle- Treasure Rm");
            locationList.Add(237, "Ultimecia Castle- Storage Room");
            locationList.Add(238, "Ultimecia Castle- Art Gallery");
            locationList.Add(239, "Ultimecia Castle- Flood Gate");
            locationList.Add(240, "Ultimecia Castle- Armory");
            locationList.Add(241, "Ultimecia Castle- Prison Cell");
            locationList.Add(242, "Ultimecia Castle- Waterway");
            locationList.Add(243, "Ultimecia Castle- Courtyard");
            locationList.Add(244, "Ultimecia Castle- Chapel");
            locationList.Add(245, "Ultimecia Castle- Clock Tower");
            locationList.Add(246, "Ultimecia Castle- Master Room");
            locationList.Add(248, "Ultimecia Castle");
            locationList.Add(249, "Commencement Room");
            locationList.Add(250, "Queen of Cards");
        }
    }
}
